# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: shoeb091
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-nodejs-http-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverlessIntro

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get


#export AWS_ACCESS_KEY_ID=AKIAI4J3ZQ3Q5Q3Q3Q3Q
#export AWS_SECRET_ACCESS_KEY=<>
#serverless deploy